export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

//tour

export const LIST_TOURS_REQUEST = "LIST_TOURS_REQUEST";
export const LIST_TOURS_SUCCESS = "LIST_TOURS_SUCCESS";
export const LIST_TOURS_FAIL = "LIST_TOURS_FAIL";

export const LIST_TOUR_REQUEST = "LIST_TOUR_REQUEST";
export const LIST_TOUR_SUCCESS = "LIST_TOUR_SUCCESS";
export const LIST_TOUR_FAIL = "LIST_TOUR_FAIL";
